const USER_ROLES = Object.freeze({
  CUSTOMER: 'CUSTOMER',
  TECHNICIAN: 'TECHNICIAN',
  PROVIDER: 'TECHNICIAN', // Canonical role is TECHNICIAN; legacy alias preserved
  ADMIN: 'ADMIN'
});

const USER_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  DEACTIVATED: 'DEACTIVATED'
});

const PROVIDER_STATUS = Object.freeze({
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED'
});

const TECHNICIAN_STATUS = PROVIDER_STATUS;

const SERVICE_PRICING_TYPE = Object.freeze({
  FIXED: 'FIXED',
  HOURLY: 'HOURLY',
  STARTING_AT: 'STARTING_AT',
  CUSTOM_ESTIMATE: 'CUSTOM_ESTIMATE'
});

const SERVICE_CATEGORY_STATUS = Object.freeze({
  ACTIVE: 'active',
  INACTIVE: 'inactive'
});

const SERVICE_STATUS = Object.freeze({
  ACTIVE: 'active',
  INACTIVE: 'inactive'
});

const SERVICE_REQUEST_STATUS = Object.freeze({
  DRAFT: 'draft',
  SUBMITTED: 'submitted',
  REVIEWING: 'reviewing',
  ESTIMATED: 'estimated',
  CANCELLED: 'cancelled',
  EXPIRED: 'expired'
});

const BOOKING_STATUS = Object.freeze({
  REQUESTED: 'REQUESTED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  SCHEDULED: 'SCHEDULED',
  INSPECTION: 'INSPECTION',
  ESTIMATE_PENDING: 'ESTIMATE_PENDING',
  ESTIMATE_SUBMITTED: 'ESTIMATE_SUBMITTED',
  ESTIMATE_APPROVED: 'ESTIMATE_APPROVED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  WORK_IN_PROGRESS: 'WORK_IN_PROGRESS',
  WORK_COMPLETED: 'WORK_COMPLETED',
  CUSTOMER_CONFIRMED: 'CUSTOMER_CONFIRMED',
  INVOICED: 'INVOICED',
  CANCELLED: 'CANCELLED',
  // Backward compatibility aliases
  COMPLETED: 'INVOICED',
  IN_PROGRESS: 'WORK_IN_PROGRESS',
  TECHNICIAN_ARRIVED: 'INSPECTION',
  COMPLETION_PENDING: 'WORK_COMPLETED',
  CUSTOMER_VERIFIED: 'CUSTOMER_CONFIRMED',
  CANCELLED_BY_CUSTOMER: 'CANCELLED',
  CANCELLED_BY_PROVIDER: 'CANCELLED'
});

const ESTIMATE_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  PENDING_CUSTOMER: 'PENDING_CUSTOMER',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED',
  SUPERSEDED: 'SUPERSEDED'
});

const ESTIMATE_ITEM_TYPE = Object.freeze({
  LABOUR: 'LABOUR',
  PART: 'PART',
  SERVICE: 'SERVICE',
  OTHER: 'OTHER'
});

const JOB_UPDATE_TYPE = Object.freeze({
  INSPECTION: 'inspection',
  WORK_STARTED: 'work_started',
  MILESTONE_REACHED: 'milestone_reached',
  SCOPE_CHANGE_REQUESTED: 'scope_change_requested',
  WORK_COMPLETED: 'work_completed',
  VERIFICATION_SUBMITTED: 'verification_submitted'
});

const INVOICE_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  ISSUED: 'ISSUED',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PAID: 'PAID',
  REFUNDED: 'REFUNDED',
  CANCELLED: 'CANCELLED'
});

const INVOICE_ITEM_TYPE = Object.freeze({
  LABOR: 'labor',
  MATERIAL: 'material',
  CHANGE_ORDER: 'change_order',
  FEE: 'fee',
  TAX: 'tax'
});

const PAYMENT_STATUS = Object.freeze({
  CREATED: 'CREATED',
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED'
});

const PAYMENT_GATEWAY = Object.freeze({
  DEMO: 'DEMO',
  RAZORPAY: 'RAZORPAY'
});

const PAYMENT_METHOD = Object.freeze({
  RAZORPAY: 'razorpay',
  BANK_TRANSFER: 'bank_transfer',
  CASH: 'cash',
  CARD: 'card',
  UPI: 'upi'
});

const REFUND_STATUS = Object.freeze({
  PENDING: 'pending',
  PROCESSED: 'processed',
  REJECTED: 'rejected'
});

const WARRANTY_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  CLAIMED: 'CLAIMED',
  VOID: 'VOID'
});

const WARRANTY_CLAIM_STATUS = Object.freeze({
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  RESOLVED: 'RESOLVED'
});

const DISPUTE_STATUS = Object.freeze({
  OPEN: 'OPEN',
  UNDER_REVIEW: 'UNDER_REVIEW',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
  // Backward compatibility aliases
  WAITING_FOR_PROVIDER: 'UNDER_REVIEW',
  WAITING_FOR_CUSTOMER: 'UNDER_REVIEW',
  REJECTED: 'CLOSED',
  CANCELLED: 'CLOSED'
});

const DISPUTE_RESOLUTION = Object.freeze({
  FULL_REFUND: 'FULL_REFUND',
  PARTIAL_REFUND: 'PARTIAL_REFUND',
  REWORK: 'REWORK',
  NO_ACTION: 'NO_ACTION'
});

const DISPUTE_REASON = Object.freeze({
  QUALITY_OF_WORK: 'QUALITY_OF_WORK',
  INCOMPLETE_WORK: 'INCOMPLETE_WORK',
  BILLING_DISCREPANCY: 'BILLING_DISCREPANCY',
  DAMAGE_CAUSED: 'DAMAGE_CAUSED',
  UNPROFESSIONAL_CONDUCT: 'UNPROFESSIONAL_CONDUCT',
  OTHER: 'OTHER'
});

const NOTIFICATION_TYPE = Object.freeze({
  BOOKING_REQUESTED: 'BOOKING_REQUESTED',
  BOOKING_ACCEPTED: 'BOOKING_ACCEPTED',
  BOOKING_REJECTED: 'BOOKING_REJECTED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  BOOKING_RESCHEDULED: 'BOOKING_RESCHEDULED',
  ESTIMATE_CREATED: 'ESTIMATE_CREATED',
  ESTIMATE_SUBMITTED: 'ESTIMATE_SUBMITTED',
  ESTIMATE_APPROVED: 'ESTIMATE_APPROVED',
  ESTIMATE_REJECTED: 'ESTIMATE_REJECTED',
  ADDITIONAL_WORK_REQUESTED: 'ADDITIONAL_WORK_REQUESTED',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  WORK_STARTED: 'WORK_STARTED',
  WORK_COMPLETED: 'WORK_COMPLETED',
  CUSTOMER_CONFIRMED: 'CUSTOMER_CONFIRMED',
  INVOICE_GENERATED: 'INVOICE_GENERATED',
  WARRANTY_AVAILABLE: 'WARRANTY_AVAILABLE',
  REVIEW_REQUESTED: 'REVIEW_REQUESTED',
  TECHNICIAN_REGISTERED: 'TECHNICIAN_REGISTERED',
  VERIFICATION_REQUESTED: 'VERIFICATION_REQUESTED',
  WARRANTY_CLAIM_CREATED: 'WARRANTY_CLAIM_CREATED',
  DISPUTE_CREATED: 'DISPUTE_CREATED',
  DISPUTE_UPDATED: 'DISPUTE_UPDATED',
  SYSTEM: 'SYSTEM'
});

const LEDGER_ENTRY_TYPE = Object.freeze({
  PAYMENT_RECEIVED: 'payment_received',
  PROVIDER_PAYOUT: 'provider_payout',
  PLATFORM_COMMISSION: 'platform_commission',
  TAX_WITHHELD: 'tax_withheld',
  REFUND_ISSUED: 'refund_issued',
  ADJUSTMENT: 'adjustment'
});

module.exports = {
  USER_ROLES,
  USER_STATUS,
  PROVIDER_STATUS,
  TECHNICIAN_STATUS,
  SERVICE_PRICING_TYPE,
  SERVICE_CATEGORY_STATUS,
  SERVICE_STATUS,
  SERVICE_REQUEST_STATUS,
  BOOKING_STATUS,
  ESTIMATE_STATUS,
  ESTIMATE_ITEM_TYPE,
  JOB_UPDATE_TYPE,
  INVOICE_STATUS,
  INVOICE_ITEM_TYPE,
  PAYMENT_STATUS,
  PAYMENT_GATEWAY,
  PAYMENT_METHOD,
  REFUND_STATUS,
  WARRANTY_STATUS,
  WARRANTY_CLAIM_STATUS,
  DISPUTE_STATUS,
  DISPUTE_RESOLUTION,
  DISPUTE_REASON,
  NOTIFICATION_TYPE,
  LEDGER_ENTRY_TYPE
};

